services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: sprintly
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
      build: ./Backend
      restart: unless-stopped
      # Make local DB dependency optional for cloud deployment
      depends_on:
        - db 
      environment:
        # Use variable substitution. If the EC2 instance injects it, use that. Otherwise, default to local.
        SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://db:5432/sprintly}
        SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-postgres}
        SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-postgres}
        JWT_SECRET: ${JWT_SECRET:-9a4f4e354567f1b9f6b9f6b9f6b9f6b9f6b9f6b9f6b9f6b9f6b9f6b9f6b9f6b9}
        JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      ports:
        - "8080:8080"

  frontend:
    build: ./Frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "1999:1999"

volumes:
  pgdata:
